### ISSUE TITLE
don't work in mobile env 

### ISSUE THREAD

**Issue by luowei-D** [apendua/meteor-mathjax#10]
It's working well in the browser, but don't work in the mobile(use cordova, both ios and android).

**Comment by apendua** [comment]
Hi! Thanks for letting me know. Can you describe some more details about the error itself. Some steps to reproduce / simple example / screenshot would also be useful.

**Comment by apendua** [comment]
@barlowluo Can you please double check if it's still an issue with the latest release?

**Comment by tonystevens** [comment]
It actually works in cordova platform. Not sure what issue @luowei-D got, but I have my meteor project running on ios-platform and I can see the latex formula rendered properly.

**Comment by apendua** [comment]
@tonystevens Yeah, same situation here. I think this issue was probably solved in the meantime.

@luowei-D Please re-open if you think it's still broken.
