### ISSUE TITLE
mhchem.js and other extensions are not loaded?

### ISSUE THREAD

**Issue by kaushik1979** [apendua/meteor-mathjax#11]
I am trying to use mhchem.js for chemistry TeX notations and it does not seem to recognize \ce and similar notifications.

Looking inside the meteor-mathjax code, I see that extensions are not specified. Can you include the following extensions (or give a way to specify extensions based on requirement)?

`
TeX: {extensions: ["mhchem.js","color.js","cancel.js","AMSmath.js","AMSsymbols.js","autobold.js","noErrors.js","noUndefined.js","default.js"]},
`

**Comment by apendua** [comment]
What API does `MathJax` provide for including those extentions?

**Comment by apendua** [comment]
@kaushik1979 There's now an option to use custom `MathJax` configuration. Please see the [readme](https://github.com/apendua/meteor-mathjax/blob/devel/README.md) for more details.
