### ISSUE TITLE
Is there a way to render based on what latex content returned from database?

### ISSUE THREAD

**Issue by tonystevens** [apendua/meteor-mathjax#16]
@apendua, is there a way to render based on what latex content returned from database?
For example, in my template I have 
`<div>{{#mathjax}}{{content}}{{/mathjax}}</div>`
and this content is from a helper function
```
Template.templatename.helpers({
  content: () => Contents.findOne().content
});
```

**Comment by apendua** [comment]
@tonystevens Yes, definitely.

However, you may want to put your content in `{{{...}}}` to prevent HTML escaping. Please let me know if it helped.

**Comment by tonystevens** [comment]
Thanks @apendua, it works. A follow up question, if the helper function returns an array of message that contains id and content (content is in latex format),
```
Template.templatename.helpers({
  messages: () => Messages.find({}) // returns [message], message {id:String, content:String}
});
```
and in the template, I have
```
<div>
{{#each message in messages}}
  {{message.id}}
  {{#mathjax}}
    {{{message.content}}}
  {{/mathjax}}
{{/each}}
</div>
```
the message.content won't render.

Do you know if there is a way to resolve this?

**Comment by tonystevens** [comment]
Never mind, I figured it out offline. Thanks, @apendua

**Comment by apendua** [comment]
@tonystevens Cool! Let's close the ticket then
