### ISSUE TITLE
markdown with mathjax

### ISSUE THREAD

**Issue by kaushik1979** [apendua/meteor-mathjax#3]
Can you help me in making these two work together? Here is what I am trying to do - 

{{#mathjax}}{{#markdown}}{{some mark-down text mixed with latex formula}}{{/markdown}}{{/mathjax}}

I am using shwdown markdown for markdown template.

**Comment by apendua** [comment]
@kaushik1979 @kaushik1979 
The recommended way to use `markdown` along with `mathjax` is by a `transform` option, e.g.
```javascript
var converter = new Showdown.converter();
var helper = new MeteorMathJax.Helper({
  transform : function (x) {
    return converter.makeHtml(x);
  },
});
Template.registerHelper('mathjax', helper.getTemplate());
```
Now you can skip the nested `markdown` helper.
