### ISSUE TITLE
is "wait=true" implemented?

### ISSUE THREAD

**Issue by tikitariki** [apendua/meteor-mathjax#8]
I used MathJax and knew you could postpone showing the text before rendering, but didn't see anything to control it in your readme, but noticed it in your source and also your example. It does not work. Is there more to it than just adding {{#mathjax wait=true}}?

Update:
If there is an Each loop inside of a Mathjax with wait=true, you get [Error] Error: {{#each}} currently only accepts arrays, cursors or falsey values.

Hmm, I'll figure this out!

**Comment by apendua** [comment]
@tikitariki Good catch! I will look into it.

**Comment by Joe312341** [comment]
Has this ever been solved?

Something like the following code will render immediately before mathjax is done processing it

  ```{{#mathjax wait=true}}
    <p>$2+3 = 5$</p>  
    {{/mathjax}}```

Thanks

**Comment by apendua** [comment]
@tikitariki I decided to get rid of this option because the latest version of `MathJax` is performing all rendering asynchronously by default and I am not sure if there's an option to change this behavior.
